Env: "dev"

DatabaseSettings:
#  DatabaseURI: "root:12312312@tcp(127.0.0.1:3306)/go_database?parseTime=true&loc=Local"
#  DatabaseURI: "root:root@tcp(mysql:3306)/go_database?parseTime=true&loc=Local"
  Host: "127.0.0.1"
#  Host: "mysql"
  Port: 3306
  DatabaseName: "go_database"
  Username: "root"
  Password: "root"
  
  
JwtSettings:
    SecretKey: "asdfgh"


RedisSettings:
  Host: "127.0.0.1"
  Port: 6379
  DatabaseName: 8
  Username: ""
  Password: ""
