Env: "dev"

DatabaseSettings:
  DatabaseURI: "root:root@tcp(127.0.0.1:3306)/go_database?parseTime=true&loc=Local"
  DatabaseName: "go_database"
  Username: "root"
  Password: "root"
  
  
JwtSettings:
    SecretKey: "asdfgh"